language: python
python:
  - 2.7
  - 3.5
env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.9
before_install:
  - wget https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.3.deb
  - sudo dpkg -i --force-confnew elasticsearch-2.3.3.deb
  - sudo service elasticsearch restart
install:
  - pip install -U setuptools
  - python bootstrap.py
  - ./bin/buildout versions:django=$DJANGO_VERSION
before_script:
  - ./bin/flake8 trampoline
  - sleep 10
script:
  - ./bin/test
notifications:
  email: false
